import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import HomeBar from "./navigation/Top5";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Js Tailwind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HomeBar />
        <div className="mb-20">{children}</div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
